version: '3'

services:
  # Frontend (React)
  frontend:
    image: node:latest
    working_dir: /app
    volumes:
      - ./frontend:/app 
    ports:
      - "3000:3000"
    command: sh -c "yarn install && yarn start"

  # Backend (Node.js with Express)
  backend:
    image: node:latest 
    working_dir: /app
    volumes:
      - ./backend:/app 
    ports:
      - "3001:3001"
    environment: 
      DB_HOST: postgres
      DB_USER: root
      DB_PASS: admin
      DB_NAME: hubbeappdb
    command: sh -c "yarn install && yarn start" 

  # PostgreSQL
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: hubbeappdb
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
    volumes: 
      - postgres-data:/var/lib/postgresql/data

  # Jest for backend tests
  jest-backend:
    image: node:latest
    working_dir: /app
    volumes:
      - ./backend:/app
    command: sh -c "yarn install && yarn test" 

volumes:
  postgres-data:
